doctrine_mongodb:
  connections:
    default:
      server: '%env(resolve:MONGODB_URL)%'
      options: {}
  default_database: rami
  document_managers:
    default:
      auto_mapping: true
      mappings:
        App\Document:
          type: attribute
          dir: '%kernel.project_dir%/src/Document'
          prefix: 'App\Document'
