
services:
  networth-php:
    build: docker/php
    container_name: networth-php
    volumes:
      - .:/var/www/symfony:delegated
    working_dir: /var/www/symfony
    networks:
      - symfony

  networth-nginx:
    build: docker/nginx
    container_name: networth-nginx
    ports:
      - "8183:80"
    volumes:
      - ./docker/nginx/sites-enabled/site.conf:/etc/nginx/sites-enabled/site.conf:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/symfony:delegated
    depends_on:
      - networth-php
    networks:
      - symfony
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: networth-database
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rami
      MONGO_INITDB_ROOT_PASSWORD: rami
      MONGO_INITDB_DATABASE: rami
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - symfony
  yarn:
    build: docker/yarn
    volumes:
      - .:/srv
    networks:
      - symfony

      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  mongodb_data:
###< doctrine/doctrine-bundle ###
networks:
  symfony:
    driver: bridge
