name: CI Symfony

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      # (Optionnel mais recommandé)
      - name: Cache Symfony
        run: php bin/console cache:warmup

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --testdox

