name: CI Symfony

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    services:
      database:
        image: mongo:7.0
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
          MONGO_INITDB_DATABASE: app_test
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --username root --password root --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
        env:
          APP_ENV: test
          MONGODB_URL: mongodb://root:root@database:${{ job.services.database.ports['27017'] }}/app_test?authSource=admin

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --testdox

